### ISSUE TITLE
Since installing klicky I get a shutdown error on homing sometimes now.

### ISSUE THREAD

**Issue by PhilBaz** [jlas1/Klicky-Probe#148]
Here is the terminal out put...

08:36:38
Internal error on command:"TEMP_PRESET"
08:36:38
Internal error on command:"G28"
08:36:38
Internal error on command:"G0"
08:36:38
Klipper state: Shutdown
08:36:38
probe: TRIGGERED
08:36:37
Homing Z
08:36:37
Homing Y
08:36:37
Homing X

[klippy.log](https://github.com/jlas1/Klicky-Probe/files/9567523/klippy.log)

**Comment by jlas1** [comment]
from your log, it seems that the culprit is the frame_expansion_compensation, try to disable that.

Receive: 99 43354.269310 43354.268959 12: seq: 12, shutdown clock=2217911076 static_string_id=Command request
Internal error on command:"G28"
Internal error on command:"TEMP_PRESET"
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/gcode.py", line 198, in _process_commands
    handler(gcmd)
  File "/home/pi/klipper/klippy/gcode.py", line 135, in <lambda>
    func = lambda params: origfunc(self._get_extended_params(params))
  File "/home/pi/klipper/klippy/extras/gcode_macro.py", line 186, in cmd
    self.template.run_gcode_from_command(kwparams)
  File "/home/pi/klipper/klippy/extras/gcode_macro.py", line 68, in run_gcode_from_command
    self.gcode.run_script_from_command(self.render(context))
  File "/home/pi/klipper/klippy/gcode.py", line 213, in run_script_from_command
    self._process_commands(script.split('\n'), need_ack=False)
  File "/home/pi/klipper/klippy/gcode.py", line 198, in _process_commands
    handler(gcmd)
  File "/home/pi/klipper/klippy/extras/homing_override.py", line 60, in cmd_G28
    self.template.run_gcode_from_command(context)
  File "/home/pi/klipper/klippy/extras/gcode_macro.py", line 68, in run_gcode_from_command
    self.gcode.run_script_from_command(self.render(context))
  File "/home/pi/klipper/klippy/gcode.py", line 213, in run_script_from_command
    self._process_commands(script.split('\n'), need_ack=False)
  File "/home/pi/klipper/klippy/gcode.py", line 198, in _process_commands
    handler(gcmd)
  File "/home/pi/klipper/klippy/extras/gcode_move.py", line 143, in cmd_G1
    self.move_with_transform(self.last_position, self.speed)
  File "/home/pi/klipper/klippy/extras/skew_correction.py", line 71, in move
    self.next_transform.move(corrected_pos, speed)
  File "/home/pi/klipper/klippy/extras/frame_expansion_compensation.py", line 187, in move
    corrected_pos = self.calc_offset(newpos)
  File "/home/pi/klipper/klippy/extras/frame_expansion_compensation.py", line 165, in calc_offset
    self.update_state()
  File "/home/pi/klipper/klippy/extras/frame_expansion_compensation.py", line 214, in update_state
    state += '(limited)' % self.max_offset
TypeError: not all arguments converted during string formatting
Internal error on command:"TEMP_PRESET"
Internal Error on WebRequest: gcode/script
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/webhooks.py", line 256, in _process_request
    func(web_request)
  File "/home/pi/klipper/klippy/webhooks.py", line 425, in _handle_script
    self.gcode.run_script(web_request.get_str('script'))
  File "/home/pi/klipper/klippy/gcode.py", line 216, in run_script
    self._process_commands(script.split('\n'), need_ack=False)
  File "/home/pi/klipper/klippy/gcode.py", line 198, in _process_commands
    handler(gcmd)
  File "/home/pi/klipper/klippy/gcode.py", line 135, in <lambda>
    func = lambda params: origfunc(self._get_extended_params(params))
  File "/home/pi/klipper/klippy/extras/gcode_macro.py", line 186, in cmd
    self.template.run_gcode_from_command(kwparams)
  File "/home/pi/klipper/klippy/extras/gcode_macro.py", line 68, in run_gcode_from_command
    self.gcode.run_script_from_command(self.render(context))
  File "/home/pi/klipper/klippy/gcode.py", line 213, in run_script_from_command
    self._process_commands(script.split('\n'), need_ack=False)
  File "/home/pi/klipper/klippy/gcode.py", line 198, in _process_commands
    handler(gcmd)
  File "/home/pi/klipper/klippy/extras/homing_override.py", line 60, in cmd_G28
    self.template.run_gcode_from_command(context)
  File "/home/pi/klipper/klippy/extras/gcode_macro.py", line 68, in run_gcode_from_command
    self.gcode.run_script_from_command(self.render(context))
  File "/home/pi/klipper/klippy/gcode.py", line 213, in run_script_from_command
    self._process_commands(script.split('\n'), need_ack=False)
  File "/home/pi/klipper/klippy/gcode.py", line 198, in _process_commands
    handler(gcmd)
  File "/home/pi/klipper/klippy/extras/gcode_move.py", line 143, in cmd_G1
    self.move_with_transform(self.last_position, self.speed)
  File "/home/pi/klipper/klippy/extras/skew_correction.py", line 71, in move
    self.next_transform.move(corrected_pos, speed)
  File "/home/pi/klipper/klippy/extras/frame_expansion_compensation.py", line 187, in move
    corrected_pos = self.calc_offset(newpos)
  File "/home/pi/klipper/klippy/extras/frame_expansion_compensation.py", line 165, in calc_offset
    self.update_state()
  File "/home/pi/klipper/klippy/extras/frame_expansion_compensation.py", line 214, in update_state
    state += '(limited)' % self.max_offset
TypeError: not all arguments converted during string formatting
Internal error on command:"G0"
Once the underlying issue is corrected, use the
"FIRMWARE_RESTART" command to reset the firmware, reload the
config, and restart the host software.
Printer is shutdown

**Comment by PhilBaz** [comment]
Ill look at that... thank you!
